server:
  port: 8082

spring:
  application:
    name: ms-cuentas-movimientos

  datasource:
    url: jdbc:postgresql://localhost:5433/db_cuentas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        auto-startup: true

banking:
  rabbitmq:
    exchange: banking.exchange
    queue: cliente.queue

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
