services:

  postgres-clientes:
    image: postgres:16
    container_name: db-clientes
    environment:
      POSTGRES_DB: db_clientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata-clientes:/var/lib/postgresql/data
      - ./docker/init/db_clientes.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-cuentas:
    image: postgres:16
    container_name: db-cuentas
    environment:
      POSTGRES_DB: db_cuentas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata-cuentas:/var/lib/postgresql/data
      - ./docker/init/db_cuentas.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: banking-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: banking-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sofka.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-clientes
      - postgres-cuentas

  ms-clientes-personas:
    build: ./ms-clientes-personas
    container_name: ms-clientes-personas
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-clientes:5432/db_clientes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      postgres-clientes:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  ms-cuentas-movimientos:
    build: ./ms-cuentas-movimientos
    container_name: ms-cuentas-movimientos
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cuentas:5432/db_cuentas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      postgres-cuentas:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pgdata-clientes:
  pgdata-cuentas:
